language: node_js
node_js:
- '6'
install:
- npm install
before_script:
- npm install -g gulp
script: gulp build
after_success:
- bash deploy.sh
env:
  global:
    secure: R5EwCfFENTgCC/MuZxExW/qPi1o0fcavzGg5GfQ1lRFs5O/Z8h33/Dzrvh51n/8Hm14iyUw6jJpPuItgPkaUnD7FR0vMWa8AvQtjvscidPKXrBl8LR8ZesbX0/DUvRmEP9scQHujk07MSI/J/Dpgcfpy2TugF4A0M7Q8gCX921RkfvgkqVD9yfaX1uCBAmXuF88oskDSHjIb5mZfzGYNE7Co5C8Os4A2FjC4Ms7p8Ip2Rs11SEs7HyzSqgkyKK/+B1u4MJJF9JYnNgiL9Q2fzAq73kH3AqAhBWrg484ww7FokURBgzP+0lkhAlupIyGqgQpidXXz6I4xemnVVFvEe6P0L+PbaSfsjQkv3N8zg5+ujMn6AjE/OZ/ci9seeV+dM0yQ9cnzu1g+5aWfhfece3c3CA8acQs2BjylJzOn9XEPlhuE4cJjvLDUJJvy40epBRJbF3qP7uCswfKEue0BZVxSiM1WoNDzM0p3ekXGrNFePP4NoBLpUEzk5PFOp2/YQT18Q+z9bnN0EjOx55RJm2xZcWv9P+u4NYZtm/hiQ/XRfYTM5k1s/VCyFr5vBXzzEfkESJ1uT87T9NTWfkJLxU9+WjXriwkS/bBqdN3uhatlD+TmJ479va1s6AGBCGsybyC4DfDsIDPQ9orllcUzqWq8Sj3Kutu1L1ceXTioqdo=
